---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/drone/autoscaler

steps:
- name: test
  pull: default
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v
  - go test -v -cover ./...

- name: test_postgres
  pull: default
  image: golang
  commands:
  - cd store
  - go test -v
  environment:
    DATABASE_CONFIG: host=postgres user=postgres password=password dbname=test sslmode=disable
    DATABASE_DRIVER: postgres

- name: test_mysql
  pull: default
  image: golang
  commands:
  - cd store
  - go test -v
  environment:
    DATABASE_CONFIG: "root:password@tcp(mysql:3306)/test?parseTime=true"
    DATABASE_DRIVER: mysql

- name: build
  pull: default
  image: golang
  commands:
  - sh .drone.sh

- name: publish
  pull: default
  image: plugins/docker
  settings:
    auto_tag: true
    repo: drone/autoscaler
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

services:
- name: postgres
  pull: default
  image: postgres:9
  environment:
    POSTGRES_DB: test
    POSTGRES_PASSWORD: password

- name: mysql
  pull: default
  image: mysql:5
  environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: password

...
